## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
matrix:
  include:
  - julia: 1.3
    os: osx
    osx_image: xcode11.3
  - julia: 1.4
    os: osx
    osx_image: xcode11.3
  - julia: nightly
    os: osx
    osx_image: xcode11.3
  allow_failures:
  - julia: nightly
notifications:
  email: false
codecov: true
env:
  global:
    - OMP_NUM_THREADS=1
